
services:
  db:
    image: postgres:latest
    container_name: db
    volumes:
      - db_data:/var/lib/postgresql
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: test123!
    networks:
      - app_network
    restart: unless-stopped

  api:
    build: ./api
    container_name: api-container
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/users || exit 1"]
      interval: 30s # Vérifie toutes les 30 secondes
      timeout: 10s  # Attend 10 secondes pour une réponse
      retries: 3    # Échoue après 3 tentatives infructueuses
      start_period: 10s # Donne 10s à l'API pour démarrer avant le 1er test
    volumes:
      - app_logs:/app/logs
    networks:
      - app_network
      - web_network
    depends_on:
      - db
    command: sh -c "sleep 5 && python app.py"
    restart: unless-stopped
    
  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    ports:
      - "8080:80" # CORRECTION DES PORTS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - web_network
    depends_on:
      - api
    restart: unless-stopped

  monitor:
    build: ./monitor
    container_name: monitor
    volumes:
      - app_logs:/logs
    restart: unless-stopped

volumes:
  db_data:
    name: db_data
  app_logs:
    name: app_logs

networks:
  web_network:
    name: web_network
  app_network:
    name: app_network
